export const suggestedMessages = [
  'I believe in you, and I know you can do this.',
  "Remember, tough times don't last, but tough people do.",
  "I am here for you, and I'll support you no matter what.",
  'You are so much stronger than you think you are.',
  'I admire your resilience and determination.',
  'I know things are hard right now, but they will get better.',
  "You are not alone, and I'm here to help in any way I can.",
  "You have so much potential, and I'm excited to see what you'll accomplish.",
  'I am proud of you for trying your best.',
  'You are capable of amazing things, and I have faith in you.',
  "Don't give up. Every small step forward counts.",
  'I appreciate you and all the positive things you bring to my life.',
  'You are not defined by your mistakes. Learn from them and keep moving forward.',
  'Remember to take care of yourself, both physically and mentally.',
  "I'm inspired by your perseverance, even in tough times.",
  'You are an amazing person, inside and out.',
  'You are capable of achieving anything you set your mind to.',
  'You have a heart of gold, and it shines through in everything you do.',
  'I am grateful for you and the positive impact you have on my life.',
  'Your hard work and dedication inspire me every day.',
  'Your presence makes the world a better place.',
  'I have complete faith in your abilities.',
  'Your kindness and compassion make a real difference in the world.',
  'You have a unique and valuable perspective on the world.',
  'You are worthy of love and respect, just as you are.',
  'Your strength and resilience are truly admirable.',
  'I admire your courage in the face of adversity.',
  'You are not alone, and I will always be here for you.',
  'Your positive attitude is infectious and inspiring.',
  "You are making a difference, even if you don't see it yet.",
  'You are capable of making your dreams a reality.',
  'Your creativity and imagination are boundless.',
  'Your intelligence and insight are truly remarkable.',
  'You have a natural talent for bringing people together.',
  'Your hard work and perseverance will pay off in the end.',
  "You have a bright future ahead of you, and I can't wait to see it unfold.",
  'Your honesty and integrity are rare and valuable traits.',
  'You are a ray of sunshine on even the cloudiest of days.',
  'You are a true friend, and I am lucky to know you.',
  'Your dedication to your goals is truly inspiring.',
  'You are a natural leader, and people look up to you.',
  'Your unique perspective on the world is something to be celebrated.',
  'You have a gift for making others feel seen and heard.',
  'Your passion and enthusiasm are contagious.',
  'You are a constant source of positivity and encouragement.',
  'Your presence fills the room with warmth and light.',
  'You have a heart full of love, and it shows in everything you do.',
  'You are capable of overcoming any obstacle that comes your way.',
  'Your determination and focus are truly impressive.',
  'You are a true inspiration to those around you.',
  'Your generosity and kindness are boundless.',
  'You are deserving of all the good things that come your way.',
  'Your hard work and dedication do not go unnoticed.',
  'You have a beautiful soul that shines through in everything you do.',
  'You are a gift to the world, and we are all lucky to know you.',
  'Your ability to persevere through difficult times is truly admirable.',
  'You have a way of making others feel valued and appreciated.',
  'Your willingness to learn and grow is a testament to your character.',
  "You are a beautiful and unique individual, and that's something to be celebrated.",
  'Your positive outlook on life is truly inspiring.',
  'You have the ability to make a real difference in the world, and I believe you will.',
  "You are a force to be reckoned with, and I have no doubt you'll achieve great things.",
  'Your sense of humor and joy for life are truly infectious.',
  'You have a talent for making others feel at ease and comfortable.',
  'You are an amazing listener, and your advice and support are always appreciated.',
  'Your courage and bravery in the face of fear is truly admirable.',
  "You are a true original, and that's something to be celebrated.",
  'You have a heart full of love and compassion, and the world needs more people like you.',
  'Your ability to adapt and thrive in new situations is truly impressive.',
  'You have a natural talent for making others feel seen and heard.',
  'Your perseverance and determination are an inspiration to us all.',
  'You have a way of bringing out the best in people, even in the toughest of situations.',
  'Your generosity and kindness have a ripple effect that extends far beyond what you can see.',
  'You have a special gift for making even the smallest moments feel meaningful and memorable.',
  'Your ability to find joy and beauty in the world is truly inspiring.',
  'You are an incredibly valuable member of any team, and your contributions are always appreciated.',
  'Your ability to stay calm and level-headed in stressful situations is truly remarkable.',
  'You have a natural talent for connecting with others and building meaningful relationships.',
  'Your thoughtfulness and attention to detail are truly impressive.',
  'You are a true innovator, always pushing the boundaries and exploring new ideas.',
  "Your creativity and imagination are limitless, and I can't wait to see where they take you.",
  'You have a magnetic personality that draws others to you.',
  'Your energy and enthusiasm are contagious, and always lift the spirits of those around you.',
  'You have a way of making even the most mundane tasks feel exciting and meaningful.',
  'Your ability to find the silver lining in any situation is truly admirable.',
  'You have a natural talent for inspiring and motivating others.',
  'Your dedication and commitment to your work is truly impressive.',
  'You are a true inspiration to anyone who has ever faced adversity.',
  'Your positivity and optimism are a breath of fresh air, and always brighten my day.',
  'You have a way of making people feel valued and appreciated, even in the smallest of interactions.',
  'Your unwavering commitment to your values and beliefs is truly admirable.',
  'You are an incredible problem solver, always finding innovative solutions to even the toughest challenges.',
  'Your ability to see the best in others is truly a gift.',
  'You have a natural talent for bringing people together, and creating a sense of community wherever you go.',
  'Your strength and resilience in the face of difficulty is truly inspiring.',
  'You have a unique perspective on the world that is always worth listening to.',
  'Your ability to inspire others to be their best selves is truly remarkable.',
  'You are an incredibly empathetic and compassionate person, and the world needs more people like you.',
  'Your curiosity and thirst for knowledge is truly admirable.',
  'You have a natural talent for leadership, and the ability to inspire others to follow your lead.',
  'Your passion and enthusiasm for life is truly infectious, and always lifts the spirits of those around you.',
  'You have a way of making others feel heard and understood, even in the toughest of situations.',
  'Your selflessness and generosity are truly inspiring, and make the world a better place.',
  'You have a unique ability to make even the most mundane tasks feel meaningful and important.',
  'Your ability to listen and offer support is truly a gift.',
  'You are a true original, and the world is a better place because of you.',
  'Your ability to inspire others to see the best in themselves is truly remarkable.',
  'You have a natural talent for making people feel welcome and included, no matter who they are.',
  'Your humility and kindness are truly admirable, and make you a role model to us.',
]

export const friends = [
  {
    id: 1,
    nameLast: 'Doe',
    nameFirst: 'John',
    name: 'John Doe',
    username: 'john321',
  },
  {
    id: 2,
    nameLast: 'Smith',
    nameFirst: 'Jane',
    name: 'Jane Smith',
    username: 'MissSmith',
  },
  {
    id: 3,
    nameLast: 'Wilson',
    nameFirst: 'Bob',
    name: 'Bob Wilson',
    username: 'WetWilly',
  },
  {
    id: 4,
    nameLast: 'Doe',
    nameFirst: 'John',
    name: 'John Doe',
    username: 'john321',
  },
  {
    id: 5,
    nameLast: 'Smith',
    nameFirst: 'Jane',
    name: 'Jane Smith',
    username: 'MissSmith',
  },
  {
    id: 6,
    nameLast: 'Wilson',
    nameFirst: 'Bob',
    name: 'Bob Wilson',
    username: 'WetWilly',
  },
  {
    id: 7,
    nameLast: 'Doe',
    nameFirst: 'John',
    name: 'John Doe',
    username: 'john321',
  },
  {
    id: 8,
    nameLast: 'Smith',
    nameFirst: 'Jane',
    name: 'Jane Smith',
    username: 'MissSmith',
  },
  {
    id: 9,
    nameLast: 'Wilson',
    nameFirst: 'Bob',
    name: 'Bob Wilson',
    username: 'WetWilly',
  },
  {
    id: 10,
    nameLast: 'Doe',
    nameFirst: 'John',
    name: 'John Doe',
    username: 'john321',
  },
  {
    id: 11,
    nameLast: 'Smith',
    nameFirst: 'Jane',
    name: 'Jane Smith',
    username: 'MissSmith',
  },
  {
    id: 12,
    nameLast: 'Wilson',
    nameFirst: 'Bob',
    name: 'Bob Wilson',
    username: 'WetWilly',
  },
]

export const archive = [
  {
    id: 2,
    message: 'I believe in you, and I know you can do this.',
    sender: 'Bob',
  },
  {
    id: 3,
    message: "Remember, tough times don't last, but tough people do.",
    sender: 'Charlie',
  },
  {
    id: 4,
    message: "I am here for you, and I'll support you no matter what.",
    sender: 'Dana',
  },
  {
    id: 5,
    message: 'You are so much stronger than you think you are.',
    sender: 'Elliot',
  },
  {
    id: 6,
    message: 'I admire your resilience and determination.',
    sender: 'Frank',
  },
  {
    id: 7,
    message: 'I know things are hard right now, but they will get better.',
    sender: 'Gina',
  },
  {
    id: 8,
    message: "You are not alone, and I'm here to help in any way I can.",
    sender: 'Henry',
  },
  {
    id: 9,
    message:
      "You have so much potential, and I'm excited to see what you'll accomplish.",
    sender: 'Ivy',
  },
  {
    id: 10,
    message: 'I am proud of you for trying your best.',
    sender: 'Jake',
  },
  {
    id: 11,
    message:
      'One two three four five six seven eight nine ten. One two three four five six seven eight nine ten. One two three four five six seven eight nine ten. One two three four five six seven eight nine ten. One two three four five six seven eight nine ten. One two three four five six seven eight nine ten. One two three four five six seven eight nine ten. One two three four five six seven eight nine ten. One two three four five six seven eight nine ten. One two three four five six seven eight nine ten',
    sender: 'Jake',
  },
]
