/* tslint:disable */
/* eslint-disable */
/**
 * Sometimes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from './configuration'
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios'
import globalAxios from 'axios'
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from './common'
import type { RequestArgs } from './base'
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError } from './base'

/**
 *
 * @export
 * @interface ProblemDetails
 */
export interface ProblemDetails {
  [key: string]: any

  /**
   *
   * @type {string}
   * @memberof ProblemDetails
   */
  type?: string | null
  /**
   *
   * @type {string}
   * @memberof ProblemDetails
   */
  title?: string | null
  /**
   *
   * @type {number}
   * @memberof ProblemDetails
   */
  status?: number | null
  /**
   *
   * @type {string}
   * @memberof ProblemDetails
   */
  detail?: string | null
  /**
   *
   * @type {string}
   * @memberof ProblemDetails
   */
  instance?: string | null
}
/**
 *
 * @export
 * @interface UserInfo
 */
export interface UserInfo {
  /**
   *
   * @type {string}
   * @memberof UserInfo
   */
  uuid?: string | null
  /**
   *
   * @type {string}
   * @memberof UserInfo
   */
  firstName?: string | null
  /**
   *
   * @type {string}
   * @memberof UserInfo
   */
  lastName?: string | null
  /**
   *
   * @type {string}
   * @memberof UserInfo
   */
  userName?: string | null
  /**
   *
   * @type {string}
   * @memberof UserInfo
   */
  email?: string | null
  /**
   *
   * @type {string}
   * @memberof UserInfo
   */
  profilePicUrl?: string | null
  /**
   *
   * @type {Array<string>}
   * @memberof UserInfo
   */
  friends?: Array<string> | null
}

/**
 * UserInfoApi - axios parameter creator
 * @export
 */
export const UserInfoApiAxiosParamCreator = function (
  configuration?: Configuration
) {
  return {
    /**
     *
     * @param {UserInfo} [userInfo]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    addUserInfo: async (
      userInfo?: UserInfo,
      options: AxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      const localVarPath = `/UserInfo`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = {
        method: 'PUT',
        ...baseOptions,
        ...options,
      }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }
      localVarRequestOptions.data = serializeDataIfNeeded(
        userInfo,
        localVarRequestOptions,
        configuration
      )

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     *
     * @param {string} [uuid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getUserInfo: async (
      uuid?: string,
      options: AxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      const localVarPath = `/UserInfo`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = {
        method: 'GET',
        ...baseOptions,
        ...options,
      }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      if (uuid != null) {
        localVarHeaderParameter['uuid'] = String(uuid)
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
  }
}

/**
 * UserInfoApi - functional programming interface
 * @export
 */
export const UserInfoApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = UserInfoApiAxiosParamCreator(configuration)
  return {
    /**
     *
     * @param {UserInfo} [userInfo]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async addUserInfo(
      userInfo?: UserInfo,
      options?: AxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserInfo>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.addUserInfo(
        userInfo,
        options
      )
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      )
    },
    /**
     *
     * @param {string} [uuid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getUserInfo(
      uuid?: string,
      options?: AxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserInfo>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getUserInfo(
        uuid,
        options
      )
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      )
    },
  }
}

/**
 * UserInfoApi - factory interface
 * @export
 */
export const UserInfoApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  const localVarFp = UserInfoApiFp(configuration)
  return {
    /**
     *
     * @param {UserInfo} [userInfo]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    addUserInfo(userInfo?: UserInfo, options?: any): AxiosPromise<UserInfo> {
      return localVarFp
        .addUserInfo(userInfo, options)
        .then((request) => request(axios, basePath))
    },
    /**
     *
     * @param {string} [uuid]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getUserInfo(uuid?: string, options?: any): AxiosPromise<UserInfo> {
      return localVarFp
        .getUserInfo(uuid, options)
        .then((request) => request(axios, basePath))
    },
  }
}

/**
 * UserInfoApi - object-oriented interface
 * @export
 * @class UserInfoApi
 * @extends {BaseAPI}
 */
export class UserInfoApi extends BaseAPI {
  /**
   *
   * @param {UserInfo} [userInfo]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UserInfoApi
   */
  public addUserInfo(userInfo?: UserInfo, options?: AxiosRequestConfig) {
    return UserInfoApiFp(this.configuration)
      .addUserInfo(userInfo, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   *
   * @param {string} [uuid]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UserInfoApi
   */
  public getUserInfo(uuid?: string, options?: AxiosRequestConfig) {
    return UserInfoApiFp(this.configuration)
      .getUserInfo(uuid, options)
      .then((request) => request(this.axios, this.basePath))
  }
}
