name: Sometimes
run-name: ${{ github.ref_name }} - ${{ github.event.head_commit.message }}
on:
  push:
  pull-request:
    - dev
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: sometimes-node-modules
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - run: npm install
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: sometimes-node-modules
      - uses: actions/cache@v3
        with:
          path: '**/coverage'
          key: sometimes-coverage-folder
      - run: npm run test
  coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
        with:
          path: '**/coverage'
          key: sometimes-coverage-folder
      - run: |
          echo ${{github.event_name}}
          echo ${{github.ref_name}}
          ls
          npm --version
