name: Sometimes
run-name: ${{ github.actor }} build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: sometimes-node-modules
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - run: npm install
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: sometimes-node-modules
      - uses: actions/cache@v3
        with:
          path: '**/coverage'
          key: sometimes-coverage-folder
      - run: npm run test
  coverage:
    needs: test
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request
    steps:
      - uses: actions/cache@v3
        with:
          path: '**/coverage'
          key: sometimes-coverage-folder
      - run: |
          ls
